version: "2"

services:
    app:
        build:
            context: docker/dev
        image: enmarche_app
        container_name: en-marche.dev
        depends_on:
            - db
            - redis
        volumes:
            - .:/app
        networks:
            - enmarche
            - default

    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root

    redis:
        image: redis:3.2

    worker-user:
        image: enmarche_app
        container_name: enmarche_worker_user
        networks:
            - enmarche
            - default
        command: sh -c "dockerize -wait tcp://rabbitmq:5672 && bin/console rabbitmq:consumer -w api_broadcast_user"
        volumes:
            - ./:/app
        depends_on:
            - db

networks:
    enmarche:
        external:
            name: enmarche
